teleop_twist_joy_node:
  ros_parameters:
    axis_linear:   # Left thumb stick vertical
      x: 1
    scale_linear:  
      x: 1.0
    scale_linear_turbo:  
      x: 1.5
    require_enable_button: false

    axis_angular:  # Left thumb stick horizontal
      yaw: 2
    scale_angular:
      yaw: 1.0

    enable_button: 2  # Left trigger button
    enable_turbo_button: 5  # Right trigger button